"""Add table educational type

Revision ID: 03e2b810b27c
Revises: df6b69702a2d
Create Date: 2025-03-25 11:44:31.933170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03e2b810b27c'
down_revision: Union[str, None] = 'df6b69702a2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('educational_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('semester_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('discipline_blocks', sa.Column('educational_type_id', sa.Integer(), nullable=False))
    op.add_column('discipline_blocks', sa.Column('semester_number', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'discipline_blocks', 'educational_types', ['educational_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'discipline_blocks', type_='foreignkey')
    op.drop_column('discipline_blocks', 'semester_number')
    op.drop_column('discipline_blocks', 'educational_type_id')
    op.drop_table('educational_types')
    # ### end Alembic commands ###
