"""Add field description in table competencies

Revision ID: 1a3afcbbc089
Revises: d53227b44aa7
Create Date: 2025-05-05 08:56:50.211530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a3afcbbc089'
down_revision: Union[str, None] = 'd53227b44aa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competencies', sa.Column('description', sa.String(length=255), nullable=False))
    op.alter_column('competencies', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=30),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('competencies', 'name',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('competencies', 'description')
    # ### end Alembic commands ###
