"""Drop unique constr in directions

Revision ID: 529924c0874d
Revises: 1a3afcbbc089
Create Date: 2025-05-05 09:04:19.042721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '529924c0874d'
down_revision: Union[str, None] = '1a3afcbbc089'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('directions_name_key', 'directions', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('directions_name_key', 'directions', ['name'])
    # ### end Alembic commands ###
