"""Add semesters_count for map_cors

Revision ID: 7c94a18a8094
Revises: 529924c0874d
Create Date: 2025-05-13 13:00:37.189161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c94a18a8094'
down_revision: Union[str, None] = '529924c0874d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('map_cors', sa.Column('semesters_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('map_cors', 'semesters_count')
    # ### end Alembic commands ###
