"""Add unique constr for codes

Revision ID: 82f82f70de04
Revises: f09a976e910c
Create Date: 2025-04-14 11:43:32.285947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82f82f70de04'
down_revision: Union[str, None] = 'f09a976e910c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'competencies', ['code'])
    op.create_unique_constraint(None, 'indicators', ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'indicators', type_='unique')
    op.drop_constraint(None, 'competencies', type_='unique')
    # ### end Alembic commands ###
