"""Add table direction map cors

Revision ID: a57efd8e75f5
Revises: 82f82f70de04
Create Date: 2025-04-23 19:09:26.479200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a57efd8e75f5'
down_revision: Union[str, None] = '82f82f70de04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('direction_map_cors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('direction_id', sa.Integer(), nullable=False),
    sa.Column('map_core_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['direction_id'], ['directions.id'], ),
    sa.ForeignKeyConstraint(['map_core_id'], ['map_cors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('discipline_blocks_direction_id_fkey', 'discipline_blocks', type_='foreignkey')
    op.drop_column('discipline_blocks', 'direction_id')
    op.drop_constraint('map_cors_direction_id_fkey', 'map_cors', type_='foreignkey')
    op.drop_column('map_cors', 'direction_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('map_cors', sa.Column('direction_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('map_cors_direction_id_fkey', 'map_cors', 'directions', ['direction_id'], ['id'])
    op.add_column('discipline_blocks', sa.Column('direction_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('discipline_blocks_direction_id_fkey', 'discipline_blocks', 'directions', ['direction_id'], ['id'])
    op.drop_table('direction_map_cors')
    # ### end Alembic commands ###
