"""Add short name in departments

Revision ID: d53227b44aa7
Revises: 8539bd9a3016
Create Date: 2025-04-29 21:54:38.180017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd53227b44aa7'
down_revision: Union[str, None] = '8539bd9a3016'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('short_name', sa.String(length=10), nullable=False))
    op.create_unique_constraint(None, 'departments', ['short_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'departments', type_='unique')
    op.drop_column('departments', 'short_name')
    # ### end Alembic commands ###
