"""create_tables

Revision ID: df6b69702a2d
Revises: 
Create Date: 2025-03-19 20:00:42.053339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df6b69702a2d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=11), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('competencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('disciplines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('competency_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=5), nullable=False),
    sa.Column('additional_competency_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['additional_competency_id'], ['competencies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discipline_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discipline_id', sa.Integer(), nullable=False),
    sa.Column('credit_units', sa.Integer(), nullable=False),
    sa.Column('assessment_type_id', sa.Integer(), nullable=False),
    sa.Column('has_coursework', sa.Boolean(), nullable=False),
    sa.Column('has_project', sa.Boolean(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('lecture_hours', sa.Integer(), nullable=False),
    sa.Column('practice_hours', sa.Integer(), nullable=False),
    sa.Column('lab_hours', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_type_id'], ['assessment_types.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['discipline_id'], ['disciplines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competency_indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competency_code_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['competency_code_id'], ['competency_codes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('discipline_block_competencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competency_code_id', sa.Integer(), nullable=False),
    sa.Column('discipline_block_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['competency_code_id'], ['competency_codes.id'], ),
    sa.ForeignKeyConstraint(['discipline_block_id'], ['discipline_blocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('discipline_block_competencies')
    op.drop_table('competency_indicators')
    op.drop_table('discipline_blocks')
    op.drop_table('competency_codes')
    op.drop_table('disciplines')
    op.drop_table('departments')
    op.drop_table('competencies')
    op.drop_table('assessment_types')
    # ### end Alembic commands ###
