"""Add map cors and activity types

Revision ID: e445154f693d
Revises: 61f5cfee8b18
Create Date: 2025-03-27 09:32:48.542249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e445154f693d'
down_revision: Union[str, None] = '61f5cfee8b18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('map_cors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('direction_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['direction_id'], ['directions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discipline_block_activity_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discipline_block_id', sa.Integer(), nullable=False),
    sa.Column('activity_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_type_id'], ['activity_types.id'], ),
    sa.ForeignKeyConstraint(['discipline_block_id'], ['discipline_blocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('discipline_blocks', sa.Column('map_core_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'discipline_blocks', 'map_cors', ['map_core_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'discipline_blocks', type_='foreignkey')
    op.drop_column('discipline_blocks', 'map_core_id')
    op.drop_table('discipline_block_activity_types')
    op.drop_table('map_cors')
    op.drop_table('activity_types')
    # ### end Alembic commands ###
