"""Add department id in disciplines table

Revision ID: f342a3eef9d2
Revises: a57efd8e75f5
Create Date: 2025-04-23 19:15:10.792248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f342a3eef9d2'
down_revision: Union[str, None] = 'a57efd8e75f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('discipline_blocks_department_id_fkey', 'discipline_blocks', type_='foreignkey')
    op.drop_column('discipline_blocks', 'department_id')
    op.add_column('disciplines', sa.Column('department_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'disciplines', 'departments', ['department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'disciplines', type_='foreignkey')
    op.drop_column('disciplines', 'department_id')
    op.add_column('discipline_blocks', sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('discipline_blocks_department_id_fkey', 'discipline_blocks', 'departments', ['department_id'], ['id'])
    # ### end Alembic commands ###
